### ISSUE TITLE
Upgrade yup peer dependency to allow v1

### ISSUE THREAD

**Issue by h-yon** [pocka/yup-locale-ja#16]
I am seeing warning from yarn like following.

```
➤ YN0060: │ my_app provides yup (<hash>) with version 1.0.2, which doesn't satisfy what yup-locale-ja requests
```

versions:
- yup 1.0.2
- yup-locale-ja 0.1.3

**Comment by pocka** [comment]
This package currently supports `yup@0.x` only. Changes are required in order to work with `yup@1.x`. See #17.

**Comment by pocka** [comment]
Support for `yup@1.x` was added in [v1.0.0](https://github.com/pocka/yup-locale-ja/blob/master/CHANGELOG.md#100---2023-03-25)
